server:
  port: 9191

# 扳手通用组件配置
# ftp文件服务
ftp:
  # 服务器地址
  host: 127.0.0.1
  # 端口号
  port: 21
  # 用户名
  userName: acrone #根据自己需求调整
  # 密码
  password: acrone #根据自己需求调整
  # 工作目录
  workingDirectory: /file/audio #根据自己需求调整
  # 编码
  encoding: utf-8
  #被动模式
  passiveMode: true
  #连接超时时间
  clientTimeout: 30000
  # 线程数
  threaNum: 1
  # 0=ASCII_FILE_TYPE(ASCII格式)，1=EBCDIC_FILE_TYPE，2=LOCAL_FILE_TYPE(二进制文件)
  transferFileType: 2
  # 是否重命名
  renameUploaded: true
  # 重新连接时间
  retryTimes: 1200
  # 缓存大小
  bufferSize: 8192
  # 最大数
  maxTotal: 50
  # 最小空闲
  minldle: 10
  # 最大空闲
  maxldle: 50
  # 最大等待时间
  maxWait: 30000
  # 池对象耗尽之后是否阻塞，maxWait < 0 时一直等待
  blockWhenExhausted: true
  # 取对象时验证
  testOnBorrow: true
  # 回收验证
  testOnReturn: true
  # 创建时验证
  testOnCreate: true
  # 空闲验证
  testWhileldle: false
  # 后进先出
  lifo: false

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml